"""add candidate_preferences

Revision ID: 78be94f61d7f
Revises: b35252db39f1
Create Date: 2026-07-23 19:01:35.560898
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '78be94f61d7f'
down_revision: str | None = 'b35252db39f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_role', sa.String(length=150), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('education', sa.String(length=255), nullable=True),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preferred_domains', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('expected_salary_min', sa.Integer(), nullable=True),
    sa.Column('expected_salary_max', sa.Integer(), nullable=True),
    sa.Column('preferred_interview_language', sa.String(length=10), nullable=False),
    sa.Column('preferred_interviewer_voice', sa.String(length=20), nullable=True),
    sa.Column('preferred_interview_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("preferred_interview_language IN ('en', 'hi')", name=op.f('chk_candidate_preferences_language')),
    sa.CheckConstraint("preferred_interview_type IN ('technical', 'behavioral', 'mixed')", name=op.f('chk_candidate_preferences_interview_type')),
    sa.CheckConstraint("preferred_interviewer_voice IN ('male', 'female')", name=op.f('chk_candidate_preferences_voice')),
    sa.CheckConstraint('expected_salary_max IS NULL OR expected_salary_min IS NULL OR expected_salary_max >= expected_salary_min', name=op.f('chk_candidate_preferences_salary_range')),
    sa.CheckConstraint('expected_salary_min IS NULL OR expected_salary_min >= 0', name=op.f('chk_candidate_preferences_salary_min')),
    sa.CheckConstraint('experience_years IS NULL OR (experience_years >= 0 AND experience_years <= 50)', name=op.f('chk_candidate_preferences_experience_years')),
    sa.CheckConstraint('graduation_year IS NULL OR (graduation_year >= 1900 AND graduation_year <= 2100)', name=op.f('chk_candidate_preferences_graduation_year')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_candidate_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_candidate_preferences_user_id'))
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.alter_column('is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)

    op.drop_table('candidate_preferences')
    # ### end Alembic commands ###
