"""add resume is_default

Revision ID: b35252db39f1
Revises: f1dbd8209123
Create Date: 2026-07-23 18:43:48.176702
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b35252db39f1'
down_revision: str | None = 'f1dbd8209123'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        # server_default backfills existing rows so the NOT NULL add is safe.
        batch_op.add_column(
            sa.Column(
                'is_default',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
