"""initial schema

Revision ID: f1dbd8209123
Revises: 
Create Date: 2026-07-23 18:17:04.699949
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1dbd8209123'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('candidate', 'admin', 'moderator', 'support')", name=op.f('chk_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('idx_users_role', ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45).with_variant(postgresql.INET(), 'postgresql'), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("event_type IN ('authentication', 'authorization', 'resume_upload', 'resume_processing', 'interview', 'evaluation', 'report', 'security', 'system', 'admin')", name=op.f('chk_audit_logs_event_type')),
    sa.CheckConstraint("severity IN ('debug', 'info', 'warning', 'error', 'critical')", name=op.f('chk_audit_logs_severity')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_event_occurred', ['event_type', 'occurred_at'], unique=False)
        batch_op.create_index('idx_audit_event_type', ['event_type'], unique=False)
        batch_op.create_index('idx_audit_occurred_at', ['occurred_at'], unique=False)
        batch_op.create_index('idx_audit_request', ['request_id'], unique=False)
        batch_op.create_index('idx_audit_resource', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index('idx_audit_severity', ['severity'], unique=False)
        batch_op.create_index('idx_audit_user', ['user_id'], unique=False)
        batch_op.create_index('idx_audit_user_occurred', ['user_id', 'occurred_at'], unique=False)

    op.create_table('resumes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('upload_status', sa.String(length=30), nullable=False),
    sa.Column('processing_status', sa.String(length=30), nullable=False),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("processing_status IN ('pending', 'processing', 'completed', 'failed')", name=op.f('chk_resumes_processing_status')),
    sa.CheckConstraint("upload_status IN ('uploaded', 'failed', 'deleted')", name=op.f('chk_resumes_upload_status')),
    sa.CheckConstraint('file_size_bytes > 0', name=op.f('chk_resumes_file_size')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes')),
    sa.UniqueConstraint('checksum_sha256', name=op.f('uq_resumes_checksum_sha256'))
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index('idx_resumes_checksum', ['checksum_sha256'], unique=False)
        batch_op.create_index('idx_resumes_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_resumes_processing_status', ['processing_status'], unique=False)
        batch_op.create_index('idx_resumes_user_id', ['user_id'], unique=False)

    op.create_table('candidate_profiles',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('profile_version', sa.Integer(), nullable=False),
    sa.Column('professional_summary', sa.Text(), nullable=True),
    sa.Column('total_experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('highest_education', sa.String(length=255), nullable=True),
    sa.Column('current_job_title', sa.String(length=255), nullable=True),
    sa.Column('current_company', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('education', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('experience', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('projects', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('certifications', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('languages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ai_confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_model_version', sa.String(length=50), nullable=True),
    sa.Column('extraction_status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("extraction_status IN ('completed', 'partial', 'failed')", name=op.f('chk_candidate_profiles_extraction_status')),
    sa.CheckConstraint('ai_confidence_score IS NULL OR (ai_confidence_score >= 0 AND ai_confidence_score <= 100)', name=op.f('chk_candidate_profiles_confidence_score')),
    sa.CheckConstraint('profile_version >= 1', name=op.f('chk_candidate_profiles_profile_version')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_candidate_profiles_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_profiles')),
    sa.UniqueConstraint('resume_id', name=op.f('uq_candidate_profiles_resume_id'))
    )
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.create_index('idx_candidate_profiles_projects', ['projects'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_candidate_profiles_resume', ['resume_id'], unique=False)
        batch_op.create_index('idx_candidate_profiles_skills', ['skills'], unique=False, postgresql_using='gin')
        batch_op.create_index('idx_candidate_profiles_status', ['extraction_status'], unique=False)
        batch_op.create_index('idx_candidate_profiles_version', ['profile_version'], unique=False)

    op.create_table('interviews',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('interview_type', sa.String(length=20), nullable=False),
    sa.Column('interviewer_voice', sa.String(length=50), nullable=True),
    sa.Column('target_role', sa.String(length=150), nullable=False),
    sa.Column('target_company', sa.String(length=150), nullable=True),
    sa.Column('expected_salary', sa.Integer(), nullable=True),
    sa.Column('experience_level', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name=op.f('chk_interviews_difficulty')),
    sa.CheckConstraint("experience_level IN ('fresher', 'junior', 'mid', 'senior')", name=op.f('chk_interviews_experience_level')),
    sa.CheckConstraint("interview_type IN ('text', 'voice')", name=op.f('chk_interviews_interview_type')),
    sa.CheckConstraint("status IN ('created', 'ready', 'in_progress', 'completed', 'cancelled', 'failed')", name=op.f('chk_interviews_status')),
    sa.CheckConstraint('answered_questions <= total_questions', name=op.f('chk_interviews_answer_count')),
    sa.CheckConstraint('expected_salary IS NULL OR expected_salary >= 0', name=op.f('chk_interviews_expected_salary')),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)', name=op.f('chk_interviews_overall_score')),
    sa.CheckConstraint('total_questions >= 0 AND answered_questions >= 0', name=op.f('chk_interviews_question_counts')),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_interviews_resume_id_resumes'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_interviews_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews'))
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index('idx_interviews_company', ['target_company'], unique=False)
        batch_op.create_index('idx_interviews_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_interviews_resume', ['resume_id'], unique=False)
        batch_op.create_index('idx_interviews_role', ['target_role'], unique=False)
        batch_op.create_index('idx_interviews_status', ['status'], unique=False)
        batch_op.create_index('idx_interviews_user', ['user_id'], unique=False)
        batch_op.create_index('idx_interviews_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('interview_questions',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('expected_answer_points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evaluation_rubric', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('estimated_time_seconds', sa.Integer(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('generation_prompt_version', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("category IN ('technical', 'behavioral', 'hr', 'system_design', 'coding', 'database', 'oop', 'operating_system', 'networking', 'aptitude', 'custom')", name=op.f('chk_interview_questions_category')),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name=op.f('chk_interview_questions_difficulty')),
    sa.CheckConstraint('estimated_time_seconds IS NULL OR estimated_time_seconds > 0', name=op.f('chk_interview_questions_estimated_time')),
    sa.CheckConstraint('question_number > 0', name=op.f('chk_interview_questions_question_number')),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_interview_questions_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_questions')),
    sa.UniqueConstraint('interview_id', 'question_number', name='uq_questions_interview_order')
    )
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.create_index('idx_questions_category', ['category'], unique=False)
        batch_op.create_index('idx_questions_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('idx_questions_interview', ['interview_id'], unique=False)
        batch_op.create_index('idx_questions_interview_order', ['interview_id', 'question_number'], unique=False)

    op.create_table('reports',
    sa.Column('interview_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('problem_solving_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weaknesses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('improvement_roadmap', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('hiring_recommendation', sa.String(length=30), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('report_model', sa.String(length=50), nullable=False),
    sa.Column('pdf_generated', sa.Boolean(), nullable=False),
    sa.Column('pdf_storage_path', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("hiring_recommendation IN ('strong_hire', 'hire', 'borderline', 'no_hire')", name=op.f('chk_reports_hiring_recommendation')),
    sa.CheckConstraint('communication_score IS NULL OR (communication_score >= 0 AND communication_score <= 100)', name=op.f('chk_reports_communication_score')),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)', name=op.f('chk_reports_overall_score')),
    sa.CheckConstraint('problem_solving_score IS NULL OR (problem_solving_score >= 0 AND problem_solving_score <= 100)', name=op.f('chk_reports_problem_solving_score')),
    sa.CheckConstraint('report_version >= 1', name=op.f('chk_reports_report_version')),
    sa.CheckConstraint('technical_score IS NULL OR (technical_score >= 0 AND technical_score <= 100)', name=op.f('chk_reports_technical_score')),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], name=op.f('fk_reports_interview_id_interviews'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports')),
    sa.UniqueConstraint('interview_id', name=op.f('uq_reports_interview_id'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('idx_reports_generated_at', ['generated_at'], unique=False)
        batch_op.create_index('idx_reports_interview', ['interview_id'], unique=False)
        batch_op.create_index('idx_reports_recommendation', ['hiring_recommendation'], unique=False)
        batch_op.create_index('idx_reports_score', ['overall_score'], unique=False)

    op.create_table('interview_answers',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('answer_type', sa.String(length=20), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('audio_storage_path', sa.Text(), nullable=True),
    sa.Column('transcription_text', sa.Text(), nullable=True),
    sa.Column('transcription_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('submission_status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("answer_type IN ('text', 'voice')", name=op.f('chk_interview_answers_answer_type')),
    sa.CheckConstraint("submission_status IN ('draft', 'submitted', 'processing', 'evaluated', 'failed')", name=op.f('chk_interview_answers_submission_status')),
    sa.CheckConstraint('response_time_seconds IS NULL OR (response_time_seconds >= 0 AND response_time_seconds <= 86400)', name=op.f('chk_interview_answers_response_time')),
    sa.CheckConstraint('transcription_confidence IS NULL OR (transcription_confidence >= 0 AND transcription_confidence <= 100)', name=op.f('chk_interview_answers_transcription_confidence')),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], name=op.f('fk_interview_answers_question_id_interview_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interview_answers')),
    sa.UniqueConstraint('question_id', name=op.f('uq_interview_answers_question_id'))
    )
    with op.batch_alter_table('interview_answers', schema=None) as batch_op:
        batch_op.create_index('idx_answers_language', ['language'], unique=False)
        batch_op.create_index('idx_answers_question', ['question_id'], unique=False)
        batch_op.create_index('idx_answers_status', ['submission_status'], unique=False)
        batch_op.create_index('idx_answers_submitted_at', ['submitted_at'], unique=False)

    op.create_table('evaluations',
    sa.Column('answer_id', sa.Uuid(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('problem_solving_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('strengths', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('weaknesses', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('improvement_suggestions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('detailed_feedback', sa.Text(), nullable=True),
    sa.Column('evaluation_model', sa.String(length=50), nullable=False),
    sa.Column('evaluation_prompt_version', sa.String(length=30), nullable=True),
    sa.Column('evaluation_duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('communication_score IS NULL OR (communication_score >= 0 AND communication_score <= 100)', name=op.f('chk_evaluations_communication_score')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)', name=op.f('chk_evaluations_confidence_score')),
    sa.CheckConstraint('evaluation_duration_ms IS NULL OR evaluation_duration_ms >= 0', name=op.f('chk_evaluations_duration')),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)', name=op.f('chk_evaluations_overall_score')),
    sa.CheckConstraint('problem_solving_score IS NULL OR (problem_solving_score >= 0 AND problem_solving_score <= 100)', name=op.f('chk_evaluations_problem_solving_score')),
    sa.CheckConstraint('technical_score IS NULL OR (technical_score >= 0 AND technical_score <= 100)', name=op.f('chk_evaluations_technical_score')),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], name=op.f('fk_evaluations_answer_id_interview_answers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluations')),
    sa.UniqueConstraint('answer_id', name=op.f('uq_evaluations_answer_id'))
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index('idx_evaluations_answer', ['answer_id'], unique=False)
        batch_op.create_index('idx_evaluations_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_evaluations_model', ['evaluation_model'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index('idx_evaluations_model')
        batch_op.drop_index('idx_evaluations_created_at')
        batch_op.drop_index('idx_evaluations_answer')

    op.drop_table('evaluations')
    with op.batch_alter_table('interview_answers', schema=None) as batch_op:
        batch_op.drop_index('idx_answers_submitted_at')
        batch_op.drop_index('idx_answers_status')
        batch_op.drop_index('idx_answers_question')
        batch_op.drop_index('idx_answers_language')

    op.drop_table('interview_answers')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('idx_reports_score')
        batch_op.drop_index('idx_reports_recommendation')
        batch_op.drop_index('idx_reports_interview')
        batch_op.drop_index('idx_reports_generated_at')

    op.drop_table('reports')
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_index('idx_questions_interview_order')
        batch_op.drop_index('idx_questions_interview')
        batch_op.drop_index('idx_questions_difficulty')
        batch_op.drop_index('idx_questions_category')

    op.drop_table('interview_questions')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index('idx_interviews_user_created')
        batch_op.drop_index('idx_interviews_user')
        batch_op.drop_index('idx_interviews_status')
        batch_op.drop_index('idx_interviews_role')
        batch_op.drop_index('idx_interviews_resume')
        batch_op.drop_index('idx_interviews_created_at')
        batch_op.drop_index('idx_interviews_company')

    op.drop_table('interviews')
    with op.batch_alter_table('candidate_profiles', schema=None) as batch_op:
        batch_op.drop_index('idx_candidate_profiles_version')
        batch_op.drop_index('idx_candidate_profiles_status')
        batch_op.drop_index('idx_candidate_profiles_skills', postgresql_using='gin')
        batch_op.drop_index('idx_candidate_profiles_resume')
        batch_op.drop_index('idx_candidate_profiles_projects', postgresql_using='gin')

    op.drop_table('candidate_profiles')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index('idx_resumes_user_id')
        batch_op.drop_index('idx_resumes_processing_status')
        batch_op.drop_index('idx_resumes_created_at')
        batch_op.drop_index('idx_resumes_checksum')

    op.drop_table('resumes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_user_occurred')
        batch_op.drop_index('idx_audit_user')
        batch_op.drop_index('idx_audit_severity')
        batch_op.drop_index('idx_audit_resource')
        batch_op.drop_index('idx_audit_request')
        batch_op.drop_index('idx_audit_occurred_at')
        batch_op.drop_index('idx_audit_event_type')
        batch_op.drop_index('idx_audit_event_occurred')

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_role')
        batch_op.drop_index('idx_users_is_active')

    op.drop_table('users')
    # ### end Alembic commands ###
